version: '3.8'

services:
  thema-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: thema-api
    container_name: thema-api
    ports:
      - "3000:3000"
    volumes:
      - ./data.json:/app/data.json
    environment:
      - NODE_ENV=production
    restart: unless-stopped
